In [10]:
#Importing the libraries required
import numpy as np
from sklearn import preprocessing

In [3]:
#Loading the training Data
train=np.loadtxt("0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
train

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [4]:
#Loading the testing Data
test=np.loadtxt("0000000000002419_test_ccpp_x_test.csv",delimiter=",")
test

array([[  11.95,   42.03, 1017.58,   90.89],
       [  12.07,   38.25, 1012.67,   81.66],
       [  26.91,   74.99, 1005.64,   78.98],
       ...,
       [  24.32,   66.25, 1009.09,   91.89],
       [  23.49,   42.8 , 1013.96,   65.31],
       [  21.76,   60.27, 1018.96,   85.06]])

In [5]:
#Checking the shape and size of data
print(train.shape)
print(test.shape)

(7176, 5)
(2392, 4)


In [6]:
#Arranging the data
X_train=train[:,:-1]
Y_train=train[:,-1]
X_test =test
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)

(7176, 4)
(7176,)
(2392, 4)


In [19]:
# Applying Gradient Descent Algorithm to the Data
def step_gradient(X,Y,m,alpha):
    m_slope=np.zeros(len(X[0]))
    for i in range(len(X)):
        x_new = X[i]
        y_new = Y[i]
        for j in range(len(x_new)):
            m_slope[j]+=(-2/len(X))*(y_new-sum(m*x_new)) * x_new[j]
    new_m=m-(alpha*m_slope)
    return new_m
    
def cost(m,x,y):
    total_cost=0
    for i in range(len(x)):
        total_cost+=(1/len(x))*((y[i]-sum(m*x[i]))**2)
    return total_cost

def gd(x,y,alpha,repeat):
    m=np.zeros(len(x[0]))
    for i in range(repeat):
        m=step_gradient(x, y, m, alpha)
        print("Loop Number", i,"--> cost =",cost(m,x,y))
    return m     

def run(x,y):
    repeat=75
    alpha=0.1
    x=np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)
    m=gd(x,y,alpha,repeat)
    return m 

In [8]:
# Feature Scaling 
features = []
for i in range(len(X_train[0])):
    for j in range(i,len(X_train[0])):
        features.append(X_train[:,i]*X_train[:,j])
features = np.array(features)
for i in features:
    X_train=np.append(X_train,i.reshape(-1,1),axis=1)
print(X_train)

[[8.58000000e+00 3.83800000e+01 1.02103000e+03 ... 1.04250226e+06
  8.61443011e+04 7.11829690e+03]
 [2.17900000e+01 5.82000000e+01 1.01721000e+03 ... 1.03471618e+06
  6.78885954e+04 4.45422760e+03]
 [1.66400000e+01 4.89200000e+01 1.01155000e+03 ... 1.02323340e+06
  7.96696780e+04 6.20313760e+03]
 ...
 [2.98000000e+01 6.93400000e+01 1.00936000e+03 ... 1.01880761e+06
  6.53459664e+04 4.19126760e+03]
 [1.63700000e+01 5.43000000e+01 1.01794000e+03 ... 1.03620184e+06
  6.47715222e+04 4.04877690e+03]
 [3.01100000e+01 6.20400000e+01 1.01069000e+03 ... 1.02149428e+06
  4.84726924e+04 2.30016160e+03]]


In [12]:
#Transforming the Data
scaler=preprocessing.StandardScaler()
scaler.fit(X_train)
X_train_new = scaler.transform(X_train)

In [13]:
X_train_new #Checking the new values of X_train

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00, ...,
         1.30316372e+00,  8.00076438e-01,  7.41910359e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01, ...,
         6.59540682e-01, -4.28576655e-01, -5.45638492e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01, ...,
        -2.89664279e-01,  3.64318663e-01,  2.99612441e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01, ...,
        -6.55515056e-01, -5.99701729e-01, -6.72727470e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01, ...,
         7.82350243e-01, -6.38363211e-01, -7.41593448e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01, ...,
        -4.33426258e-01, -1.73531383e+00, -1.58670195e+00]])

In [20]:
m_new=run(X_train_new,Y_train)

Loop Number 0 --> cost = 132332.28533832615
Loop Number 1 --> cost = 84686.40853912466
Loop Number 2 --> cost = 54200.09904237565
Loop Number 3 --> cost = 34692.47518910894
Loop Number 4 --> cost = 22209.441518282096
Loop Number 5 --> cost = 14221.222142956352
Loop Number 6 --> cost = 9109.203021089681
Loop Number 7 --> cost = 5837.704006065693
Loop Number 8 --> cost = 3744.012095350955
Loop Number 9 --> cost = 2404.0548860242693
Loop Number 10 --> cost = 1546.4591718490155
Loop Number 11 --> cost = 997.5630357960288
Loop Number 12 --> cost = 646.2313011272885
Loop Number 13 --> cost = 421.34149079717685
Loop Number 14 --> cost = 277.37698546177313
Loop Number 15 --> cost = 185.2077698022464
Loop Number 16 --> cost = 126.19069727997994
Loop Number 17 --> cost = 88.39396301684997
Loop Number 18 --> cost = 64.18092077559004
Loop Number 19 --> cost = 48.663802174716906
Loop Number 20 --> cost = 38.714132861732665
Loop Number 21 --> cost = 32.32941401241289
Loop Number 22 --> cost = 28.227

In [21]:
#Feature Scaling for test data and finding Y_Pred using m_new
features_test=[]
for i in range(len(X_test[0])):
    for j in range(i,len(X_test[0])):
        features_test.append(X_test[:,i]*X_test[:,j])
features_test = np.array(features_test)
for i in features_test:
    X_test=np.append(X_test,i.reshape(-1,1),axis=1)
X_test_new = scaler.transform(X_test)
X_test_new=np.append(X_test_new,np.ones(len(X_test_new)).reshape(-1,1),axis=1)
Y_Pred=[]
for i in X_test_new:
    Y_Pred.append(sum(m_new*i))
for i in Y_Pred:
    print(i)
Y_Pred=np.array(Y_Pred)

471.14289463254283
471.87165372355923
432.7807714471095
456.41732687161874
463.7057346802152
447.69984385606926
479.79647248759784
446.1847487430954
486.53480965221985
439.62217858139115
434.1456780933196
429.79999551419
471.62505829809896
463.0079233399059
444.20607252251483
456.1430851467378
486.848521957474
447.42203171131507
425.23400942536
440.1108794016425
438.43954260560355
484.8163718179181
459.9098228387476
476.59530806869196
430.46049476212454
435.0494016889988
468.7965018208106
470.90777064858827
433.5105042123173
477.2325952609021
442.8050533881231
431.39014593634244
449.64975845906963
471.1315940014612
469.6398486978125
474.0867727062232
446.205719260291
454.94620481684444
445.0577880445265
482.87156450880093
465.4142550137724
432.31406398125563
474.1515698563538
468.55663254871376
461.1170183622548
480.27473424878485
435.92563937828527
429.488750602579
439.76447972605547
477.5387014402594
474.61190044429026
465.8327653865986
467.05590599528307
434.55039000974773
464.47732

464.57652024593517
438.46487595363845
468.7025785766095
425.68210783817165
447.8035234410356
439.61580498664375
486.49729055784013
456.4146222916129
435.1605127811256
440.16396578808417
477.58103882858853
436.74534503575865
460.52010723422364
466.50532073834916
451.23649845236554
448.11425748166886
470.85646426934346
464.1265921290699
439.954237155953
430.8724901934786
445.6391671487449
462.7676907812055
432.4199738213325
478.4874169872998
479.9271034262031
468.11439144701393
482.42448680930727
452.8964979779217
442.4701790940681
476.5778324163881
478.3609773032381
445.54415448038935
477.19509820500843
441.00823642361445
433.61795014800214
431.4624446259718
462.9287549070944
484.06502446495267
463.76257012858406
453.8446649372504
445.46783350371453
437.6448709278096
473.3259238739643
438.96023855395475
468.1608574000578
448.94927564247126
443.2980752548469
439.8250185065114
471.67998573128455
480.04042945960373
431.35823280470333
473.33297345016
430.8726261239077
468.54410611877967
465

In [23]:
#Saving the predicted data
np.savetxt(X=Y_Pred,fname='data.csv',delimiter=",",fmt='%.5f')